### PR TITLE
Molecule

### PR DESCRIPTION
**Pull request by marcgrue**

### CODE REVIEW

**Comment by SethTisue** [comment]
you need to modify template.md — README.md is automatically generated

I'll go add a note about this to the top of README.md

**Comment by SethTisue** [comment]
#502

**Comment by marcgrue** [comment]
Ah, thanks, Seth - read the instructions about the pull request in the bottom of the readme. Would be useful to have instructions at the top! Maybe a little 1-2-3 guide?

Do I leave my current modified readme unchanged or should I also remove the line I added?

**Comment by marcgrue** [comment]
Ah, your clarifications is super clear, thanks

**Comment by marcgrue** [comment]
Ok now?

**Comment by SethTisue** [comment]
this won't show up in README.md immediately. @sake92 is going to see if we can have GitHub Actions do the updates on a schedule. otherwise, we'll get it in the next manual run of the script.

**Comment by marcgrue** [comment]
Thanks for the merge and info! And thanks for your work with this awesome list!

**Pull request merged**
