### PR TITLE
DIStage and LogStage - zero-cost structural logger and DI framework

### PR DESCRIPTION
**Pull request by pshirshov**

### CODE REVIEW

**Comment by longcao** [comment]
Hey, sorry for the slow response but thanks for the contribution!

It looks like these entries point to the same URL - are they subprojects in the same repo?

**Comment by pshirshov** [comment]
Hi,

yup, there are several different subprojects in the same repo. We are going to split them later but at this point it's lot cheaper to keep them together.

**Comment by longcao** [comment]
Cool, I'll merge this now. In the future if you split these out to different places feel free to submit another PR.

**Comment by pshirshov** [comment]
Thank you. Of course will do.

**Pull request merged**
