### PR TITLE
Use GitHub Shields

### PR DESCRIPTION
**Pull request by benash**
Here's a first crack at part of #441 including stargazer and commit activity info in a new table format. I haven't yet adjusted anything in `metadata.py`, but maybe some of that functionality can go away if this design works well.

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM! though I'd be hesitant to merge it without accompanying updates to the automation

**Comment by benash** [comment]
I'll take a look at what might be involved with updating that.

**Comment by benash** [comment]
@SethTisue Ready for you to take a look.

Now that we're using shields, we don't need to automate adding stargazer counts or commit activity. But I'm now automatically pulling project descriptions as well as warning if a project is archived or inactive (no pushes in last 180 days).

I'm proposing a shift here from the prior automation approach of parsing the README file, adjusting info, and rewriting the same file. Because the new format is heavier-weight (now containing markdown tables and shields images/URLs), I made `template.md` using some shorthand that should make it easier to view diffs and reduce the likelihood of typos. A downside is that contributors would need to run automation to update README.md. 

Let me know your thoughts. I've also properly merged in recent commits.

**Comment by SethTisue** [comment]
hi, sorry for neglecting this for so long. would you mind updating it, and then I'll merge it promptly before any more merge conflicts ensue?

also, would you be interested in becoming a maintainer in this repo? perhaps @lauris would be willing to add you. I never really intended to become the only person available to merge PRs here :-)

**Comment by benash** [comment]
@SethTisue hey, I'd be open to becoming a maintainer. The main thing I'd need from you and @lauris is how we're deciding what we want added/removed from this list. I think keeping it clean (by removing repos that are inactive, etc.) is an important part of maintenance.

**Comment by SethTisue** [comment]
let's see if @lauris pipes up — it's really his repo

**Comment by SethTisue** [comment]
re: maintainership let's see if @lauris pipes up — it's really his repo

(I'm willing to merge this PR regardless, once it's been updated; I don't see anything to object to here.)

**Comment by benash** [comment]
@SethTisue Just updated.

**Comment by SethTisue** [comment]
epic! 🎉

**Pull request merged**
