### PR TITLE
add google service clients

### PR DESCRIPTION
**Pull request by allquantor**
Add clients for google cloud services .

### CODE REVIEW

**Comment by longcao** [comment]
Thanks for the contribution? In the interest of not having a line for every client, could this perhaps be one entry for https://github.com/toknapp/google4s, with a description like "Scala wrapper for various Google Cloud services"?

**Comment by allquantor** [comment]
I thought it would be more descriptive and I had easier time to find the appropriate categories. Sure I can do that, what is the appropriate category?

**Comment by longcao** [comment]
Yeah I can see that, let's consolidate to one line, especially if you are to add more wrappers. 

Since there's no great category for this you can feel free to create a new one or put it under https://github.com/lauris/awesome-scala#misc.

Thanks!

**Comment by allquantor** [comment]
Done

**Pull request merged**
