### PR TITLE
remove resources section

### PR DESCRIPTION
**Pull request by SethTisue**
no one is bothering to maintain this it has become full of stale links. I suggest we keep the repo focused on libraries.

I would support a PR that re-added it if someone submits one that includes only up-to-date links that are not too specific (as per my comments on #495)

### CODE REVIEW

**Comment by SethTisue** [comment]
(I won't merge this in less than two weeks, to give time for input.)

**Comment by SethTisue** [comment]
perhaps we should include a link to https://www.scala-lang.org/community/, which is kept reasonably up-to-date (by me, mostly)

**Comment by sake92** [comment]
Many other awesome lists do have this section..  
The scala-lang is a bit too official for lot of the content mentioned here.
If they are stale we should just remove them.. 😃

**Comment by SethTisue** [comment]
maybe someone watching this repo would like to go through and remove the stale ones?

**Comment by sake92** [comment]
Can we define what stale means? Scala 2.11? Only recent 2 versions of Play framework? We'd need at least some heuristics.

**Comment by SethTisue** [comment]
for blogs, if there haven't been any posts in a year, perhaps? for the others, someone will just have to make judgment calls

**Comment by SethTisue** [comment]
instead: #497

**Pull request closed without merging**
