### PR TITLE
Point to official couriser repository

### PR DESCRIPTION
**Pull request by txdv**
I noticed that it is pointed to a forked version

### CODE REVIEW

**Comment by SethTisue** [comment]
good catch, thanks!

but: please modify template.md, not README.md. the latter is automatically generated.

**Comment by SethTisue** [comment]
ping

**Comment by txdv** [comment]
Ok, i'll do that

**Comment by txdv** [comment]
do I need to run the script or is it run automatically?

**Comment by SethTisue** [comment]
it will be run automatically overnight.

thank you!

**Pull request merged**
