### PR TITLE
update stars for hamsters

### PR DESCRIPTION
**Pull request by loicdescotte**
I'm not sure about the second number, is it the number of forks?

### CODE REVIEW

**Comment by longcao** [comment]
I think it's something like "days since last activity" but since we don't really refresh this that often it's not super useful.

**Comment by loicdescotte** [comment]
OK thanks :) 
So I've updated it accordingly.

**Comment by longcao** [comment]
Thanks!

**Comment by loicdescotte** [comment]
Thanks!

**Pull request merged**
