### PR TITLE
Added lucene4s, neo4akka, ScalaRelational, youi, scribe, mailgun4s, m…

### PR DESCRIPTION
**Pull request by darkfrog26**
Added lucene4s, neo4akka, ScalaRelational, youi, scribe, mailgun4s, media4s, pdf4s, powerscala, and jefe.

### CODE REVIEW

**Comment by longcao** [comment]
Cool, thank you!

**Comment by ScalaWilliam** [comment]
I'd recommend some README.md files on how to get started with these projects.

**Comment by darkfrog26** [comment]
@ScalaWilliam thanks, that's a very good point, I will get to that.

**Comment by ScalaWilliam** [comment]
Thanks, that looks great 👍

**Pull request merged**
