### PR TITLE
Note that coursier is built in now.

### PR DESCRIPTION
**Pull request by justinpitts**

### CODE REVIEW

**Comment by SethTisue** [comment]
it's certainly notable that coursier is built-in to sbt. but coursier has other uses as well and remains of independent interest. it's useful as a command line tool, as a library, and so forth.

this is probably mergeable regardless, but perhaps there's an even better wording?

**Comment by justinpitts** [comment]
As a sbt-plugin, I'm not sure there's much more to say - if you're using sbt >= 1.3.0, you don't need the plugin. Should it be added to the tools section instead/also?

**Comment by alexarchambault** [comment]
Moving it to the tools section would make sense, yes.

**Comment by justinpitts** [comment]
Sorry - *move* or *add* ?

**Comment by alexarchambault** [comment]
Adding to tools along with the additional comment in the sbt section (state of the PR as of writing this) is fine by me.

**Pull request merged**
