### PR TITLE
Added Codacy to testing tools

### PR DESCRIPTION
**Pull request by paulblei**
Codacy is a free continuous static analysis tool for Scala open source projects

### CODE REVIEW

**Comment by wookietreiber** [comment]
Shouldn't there be an extra category for static analysis? (including maybe linter, abide, scalastyle, wartremover)

**Comment by paulblei** [comment]
Indeed. Testing is probably not the best category for that

**Comment by lauris** [comment]
Yes, please create a new category for Codacy as part of this PR. I think for now the category could be "Tools", because that would cover more entries than "Static analysis tools" which is a bit too specific.

**Comment by paulblei** [comment]
do you need me to change anything else in the PR?

**Pull request merged**
